### Finding Similar Movies

We'll start by loading up the MovieLens dataset. Using Pandas, we can very quickly load the rows of the u.data and u.item files that we care about, and merge them together so we can work with movie names instead of ID's. (In a real production job, you'd stick with ID's and worry about the names at the display layer to make things more efficient. But this lets us understand what's going on better for now.)

In [28]:
import pandas as pd

col_name = ['movie_id','movie_title','movie_genre']
movies = pd.read_csv('movies.dat', sep='::', names=col_name, usecols=range(3))

movies

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.

,movie_id,movie_title,movie_genre
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Animation|Children's
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Drama|Thriller
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Thriller
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action
20,21,Get Shorty (1995),Action|Comedy|Drama
21,22,Copycat (1995),Crime|Drama|Thriller
22,23,Assassins (1995),Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Drama
27,28,Persuasion (1995),Romance
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama
...,...,...,...
3853,3923,Return of the Fly (1959),Horror|Sci-Fi
3854,3924,Pajama Party (1964),Comedy
3855,3925,Stranger Than Paradise (1984),Comedy
3856,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi
3857,3927,Fantastic Voyage (1966),Adventure|Sci-Fi
3858,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror
3859,3929,"Bank Dick, The (1940)",Comedy
3860,3930,"Creature From the Black Lagoon, The (1954)",Horror
3861,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi
3862,3932,"Invisible Man, The (1933)",Horror|Sci-Fi
3863,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi
3864,3934,Kronos (1957),Sci-Fi
3865,3935,Kronos (1973),Horror
3866,3936,"Phantom of the Opera, The (1943)",Drama|Thriller
3867,3937,Runaway (1984),Sci-Fi|Thriller
3868,3938,"Slumber Party Massacre, The (1982)",Horror
3869,3939,"Slumber Party Massacre II, The (1987)",Horror
3870,3940,"Slumber Party Massacre III, The (1990)",Horror
3871,3941,Sorority House Massacre (1986),Horror
3872,3942,Sorority House Massacre II (1990),Horror
3873,3943,Bamboozled (2000),Comedy
3874,3944,Bootmen (2000),Comedy|Drama
3875,3945,Digimon: The Movie (2000),Adventure|Animation|Children's
3876,3946,Get Carter (2000),Action|Drama|Thriller
3877,3947,Get Carter (1971),Thriller
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [34]:
user_col = ['user_id','user_gender','user_age']
users = pd.read_csv('users.dat', sep='::',names = user_col, usecols=range(3))
users

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

      user_id user_gender  user_age
0           1           F         1
1           2           M        56
2           3           M        25
3           4           M        45
4           5           M        25
5           6           F        50
6           7           M        35
7           8           M        25
8           9           M        25
9          10           F        35
10         11           F        25
11         12           M        25
12         13           M        45
13         14           M        35
14         15           M        25
15         16           F        35
16         17           M        50
17         18           F        18
18         19           M         1
19         20           M        25
20         21           M        18
21         22           M        18
22         23           M        35
23         24           F        25
24         25           M        18
25         26           M        25
26         27           M        25
27         28           F        25
28         29           M        35
29         30           F        35
...       ...         ...       ...
6010     6011           M        35
6011     6012           M        35
6012     6013           F        25
6013     6014           M        45
6014     6015           F        25
6015     6016           M        45
6016     6017           F        35
6017     6018           M        35
6018     6019           M        25
6019     6020           M        50
6020     6021           M        25
6021     6022           M        25
6022     6023           M        25
6023     6024           M        25
6024     6025           F        25
6025     6026           M        35
6026     6027           M        18
6027     6028           M        18
6028     6029           F        25
6029     6030           M        25
6030     6031           F        18
6031     6032           M        45
6032     6033           M        50
6033     6034           M        25
6034     6035           F        25
6035     6036           F        25
6036     6037           F        45
6037     6038           F        56
6038     6039           F        45
6039     6040           M        25

[6040 rows x 3 columns]

In [35]:
ratings_col = ['user_id','movie_id','ratings']
ratings = pd.read_csv('ratings.dat',sep='::',names = ratings_col, usecols=range(3))
ratings

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

         user_id  movie_id  ratings
0              1      1193        5
1              1       661        3
2              1       914        3
3              1      3408        4
4              1      2355        5
5              1      1197        3
6              1      1287        5
7              1      2804        5
8              1       594        4
9              1       919        4
10             1       595        5
11             1       938        4
12             1      2398        4
13             1      2918        4
14             1      1035        5
15             1      2791        4
16             1      2687        3
17             1      2018        4
18             1      3105        5
19             1      2797        4
20             1      2321        3
21             1       720        3
22             1      1270        5
23             1       527        5
24             1      2340        3
25             1        48        5
26             1      1097        4
27             1      1721        4
28             1      1545        4
29             1       745        3
...          ...       ...      ...
1000179     6040      2762        4
1000180     6040      1036        3
1000181     6040       508        4
1000182     6040      1041        4
1000183     6040      3735        4
1000184     6040      2791        4
1000185     6040      2794        1
1000186     6040       527        5
1000187     6040      2003        1
1000188     6040       535        4
1000189     6040      2010        5
1000190     6040      2011        4
1000191     6040      3751        4
1000192     6040      2019        5
1000193     6040       541        4
1000194     6040      1077        5
1000195     6040      1079        2
1000196     6040       549        4
1000197     6040      2020        3
1000198     6040      2021        3
1000199     6040      2022        5
1000200     6040      2028        5
1000201     6040      1080        4
1000202     6040      1089        4
1000203     6040      1090        3
1000204     6040      1091        1
1000205     6040      1094        5
1000206     6040       562        5
1000207     6040      1096        4
1000208     6040      1097        4

[1000209 rows x 3 columns]

In [39]:
ratings_by_user = pd.merge(movies,ratings)
ratings_by_user.head()

   movie_id       movie_title                  movie_genre  user_id  ratings
0         1  Toy Story (1995)  Animation|Children's|Comedy        1        5
1         1  Toy Story (1995)  Animation|Children's|Comedy        6        4
2         1  Toy Story (1995)  Animation|Children's|Comedy        8        4
3         1  Toy Story (1995)  Animation|Children's|Comedy        9        5
4         1  Toy Story (1995)  Animation|Children's|Comedy       10        5

Now the amazing pivot_table function on a DataFrame will construct a user / movie rating matrix. Note how NaN indicates missing data - movies that specific users didn't rate.

In [44]:
movieRatings = ratings_by_user.pivot_table(index = ['user_id'], columns = ['movie_title'], values = 'ratings')
movieRatings

movie_title,"$1,000,000 Duck (1971)",'Night Mother (1986),'Til There Was You (1997),"'burbs, The (1989)",...And Justice for All (1979),1-900 (1994),10 Things I Hate About You (1999),101 Dalmatians (1961),101 Dalmatians (1996),12 Angry Men (1957),...,"Young Poisoner's Handbook, The (1995)",Young Sherlock Holmes (1985),Young and Innocent (1937),Your Friends and Neighbors (1998),Zachariah (1971),"Zed & Two Noughts, A (1985)",Zero Effect (1998),Zero Kelvin (Kj�rlighetens kj�tere) (1995),Zeus and Roxanne (1997),eXistenZ (1999)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,4.0,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,4.0
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6016,NaN,NaN,NaN,2.0,NaN,NaN,NaN,3.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,4.0
6017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6025,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6036,NaN,3.0,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
6037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Let's extract a Series of users who rated Young Sherlock Holmes (1985):

In [49]:
sherlockRatings = movieRatings['Young Sherlock Holmes (1985)']
sherlockRatings

user_id
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13      2.0
14      NaN
15      NaN
16      NaN
17      NaN
18      4.0
19      3.0
20      NaN
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
30      NaN
       ...
6011    NaN
6012    NaN
6013    NaN
6014    NaN
6015    NaN
6016    NaN
6017    NaN
6018    NaN
6019    NaN
6020    NaN
6021    NaN
6022    NaN
6023    NaN
6024    NaN
6025    NaN
6026    NaN
6027    NaN
6028    NaN
6029    NaN
6030    NaN
6031    NaN
6032    NaN
6033    NaN
6034    NaN
6035    NaN
6036    3.0
6037    NaN
6038    NaN
6039    3.0
6040    NaN
Name: Young Sherlock Holmes (1985), Length: 6040, dtype: float64

In [50]:
sherlockRatings.mean()

3.390501319261214

Pandas' corrwith function makes it really easy to compute the pairwise correlation of Young Sherlock Holmes (1985)' vector of user rating with every other movie! After that, we'll drop any results that have no data, and construct a new DataFrame of movies and their correlation score (similarity) to Young Sherlock Holmes (1985):

In [51]:
similarMovies = movieRatings.corrwith(sherlockRatings)
similarMovies = similarMovies.dropna()
df = pd.DataFrame(similarMovies)
df.head(10)

/usr/local/lib/python3.6/site-packages/numpy/lib/function_base.py:3175: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/usr/local/lib/python3.6/site-packages/numpy/lib/function_base.py:3109: RuntimeWarning: divide by zero encountered in double_scalars
  c *= 1. / np.float64(fact)

                                          0
movie_title
$1,000,000 Duck (1971)            -0.106243
'Night Mother (1986)              -0.276359
'Til There Was You (1997)         -0.016137
'burbs, The (1989)                 0.278425
...And Justice for All (1979)      0.052517
10 Things I Hate About You (1999)  0.185754
101 Dalmatians (1961)              0.013905
101 Dalmatians (1996)              0.059504
12 Angry Men (1957)                0.281127
13th Warrior, The (1999)           0.231933

(That warning is safe to ignore.) Let's sort the results by similarity score, and we should have the movies most similar to Young Sherlock Holmes (1985)! Except... we don't. These results make no sense at all! This is why it's important to know your data - clearly we missed something important.

In [52]:
similarMovies.sort_values(ascending=False)

movie_title
Tie That Binds, The (1995)                                                      1.000000
Golden Earrings (1947)                                                          1.000000
Steam: The Turkish Bath (Hamam) (1997)                                          1.000000
Native Son (1986)                                                               1.000000
Young Sherlock Holmes (1985)                                                    1.000000
Trick or Treat (1986)                                                           1.000000
School of Flesh, The (L' �cole de la chair) (1998)                              1.000000
Source, The (1999)                                                              1.000000
Beyond Silence (1996)                                                           1.000000
Infinity (1996)                                                                 1.000000
Born American (1986)                                                            1.000000
My Life and Times With Antonin Artaud (En compagnie d'Antonin Artaud) (1993)    1.000000
Loaded (1994)                                                                   1.000000
Original Gangstas (1996)                                                        1.000000
Kissed (1996)                                                                   1.000000
Human Traffic (1999)                                                            1.000000
Sticky Fingers of Time, The (1997)                                              1.000000
Retro Puppetmaster (1999)                                                       1.000000
Bait (2000)                                                                     1.000000
Montana (1998)                                                                  1.000000
Office Killer (1997)                                                            1.000000
Leading Man, The (1996)                                                         1.000000
Late August, Early September (Fin ao�t, d�but septembre) (1998)                 1.000000
No Looking Back (1998)                                                          1.000000
Julien Donkey-Boy (1999)                                                        1.000000
Nelly & Monsieur Arnaud (1995)                                                  1.000000
About Adam (2000)                                                               1.000000
Bossa Nova (1999)                                                               1.000000
War at Home, The (1996)                                                         1.000000
Kids of the Round Table (1995)                                                  1.000000
                                                                                  ...
Two Thousand Maniacs! (1964)                                                   -0.816497
Roadside Prophets (1992)                                                       -0.866025
Losing Chase (1996)                                                            -0.866025
Kika (1993)                                                                    -0.866025
Joe the King (1999)                                                            -0.866025
Line King: Al Hirschfeld, The (1996)                                           -0.866025
Niagara, Niagara (1997)                                                        -0.866025
Specials, The (2000)                                                           -0.866025
Real Blonde, The (1997)                                                        -0.880705
In Crowd, The (2000)                                                           -0.904534
Temptress Moon (Feng Yue) (1996)                                               -1.000000
Conceiving Ada (1997)                                                          -1.000000
Suburbans, The (1999)                                                          -1.000000
Dear Jesse (1997)                                                              -1.000000
Woman of Paris, A (1923)                                                       -1.000000
Hard Core Logo (1996)                                                          -1.000000
Molly (1999)                                                                   -1.000000
West Beirut (West Beyrouth) (1998)                                             -1.000000
Gumby: The Movie (1995)                                                        -1.000000
Mummy's Ghost, The (1944)                                                      -1.000000
Love Serenade (1996)                                                           -1.000000
Glass Shield, The (1994)                                                       -1.000000
Ogre, The (Der Unhold) (1996)                                                  -1.000000
On Our Merry Way (1948)                                                        -1.000000
Twin Town (1997)                                                               -1.000000
Wings of Courage (1995)                                                        -1.000000
Man of No Importance, A (1994)                                                 -1.000000
Let's Talk About Sex (1998)                                                    -1.000000
Stiff Upper Lips (1998)                                                        -1.000000
Power 98 (1995)                                                                -1.000000
Length: 3191, dtype: float64